import { useTranslation, i18n } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppDispatch } from 'redux/store';
import Head from 'next/head';

// constants

// Components
import Button from 'components/Basic/Button';
import Container from 'layout/Container';
import Table from 'components/Basic/Table';
import { appSlice } from 'redux/slices';

import { useRouter } from 'next/router';
import i18nConfig from '../../i18n';
import Image from 'next/image';
import {
  Box,
  Divider,
  Grid,
  Typography,
  useMediaQuery,
  useTheme,
  Rating,
  Stack,
} from '@mui/material';
import Link from 'components/Basic/Link';
import { useCallback, useMemo, useState, useEffect } from 'react';
import axios from 'axios';
import CardsSwiper from 'components/Templates/CardsSwiper';
import 'keen-slider/keen-slider.min.css';
import { decimalEmitter } from 'consts/decimal';
import Banner from 'components/Basic/Banner/Banner';
import VideoModal from 'components/Basic/videoModal/VideoModal';
import Carousels from 'components/Molecules/Card/card';
import styled from '@emotion/styled';
import Carousel from 'react-multi-carousel';

type HomeProps = {
  locale: string;
};

const Home = () => {
  const { t } = useTranslation('common');
  const [priceCur, setPriceCur] = useState('irt');
  const router = useRouter();
  const matches = useMediaQuery((theme) => theme.breakpoints.up('lg'), {
    noSsr: true,
  });

  const ultraLarge = useMediaQuery('(min-width:3000px)', {
    noSsr: true,
  });

  const [chartData, setChartData] = useState<[any]>();
  const [isOpen, setIsOpen] = useState<boolean>(false);
  const [url, setUrl] = useState<string>('');

  const { locale, query, asPath, pathname } = router;

  const api = async () => {
    const data = await axios.get(
      'https://api.maxpool.ir/mainpage/binance-api/get-all-symbols-socket/',

      {
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
          'Access-Control-Allow-Origin': '*',
        },
      },
    );
    setChartData(data.data);
  };

  useEffect(() => {
    api();
    setInterval(() => {
      api();
    }, 180000);

    return () => clearInterval();
  }, []);

  const tableCoin = ['BTC', 'ETH', 'TRX', 'BNB', 'USDT', 'SHIB'];
  const cardCoin = ['LINK', 'ADA', 'AAVE', 'DOT', 'BNB'];

  const onTetherClick = (name) => {
    setPriceCur(name);
  };

  const onDetailClick = () => {
    router.push('/pdp');
  };

  const video = [
    'https://www.aparat.com/video/video/embed/videohash/ohf1G/vt/frame',
    'https://www.aparat.com/video/video/embed/videohash/7ZBp3/vt/frame',
    'https://www.aparat.com/video/video/embed/videohash/qYC7h/vt/frame',
  ];

  const onModalOpen = (name) => {
    video.map((item, index) => {
      if (name === index) {
        setIsOpen(true);
        setUrl(item);
      }
    });
  };

  // test
  return (
    <div>
      <Head>
        <title> dental</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* table section Banner */}

      <Box component="div">
        <Banner />
        <Box
          sx={{
            height: '560px',
            position: 'absolute',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'flex-start',
            flexDirection: 'column',
            left: 0,
            right: 0,
            margin: '0 55px',
            top: '2vh',
          }}
        >
          <Typography
            variant="h4"
            component="h1"
            sx={{
              color: '#ffff',
              textAlign: 'left',
              fontWeight: '700',
              width: { xs: '50%', lg: '20%' },
            }}
          >
            The Days Of Covering Your Smile Are Over
          </Typography>
          <Button
            sx={{
              margin: '2% 0',
              borderRadius: '5px',
              backgroundColor: '#4252FA',
            }}
          >
            Contact Us
          </Button>
        </Box>
      </Box>
      <Box
        sx={{
          marginTop: '65Vh',
          marginBottom: '100px',
          textAlign: 'center',
          color: '#323232',
        }}
      >
        <Typography variant="h5" gutterBottom component="div">
          Lorem ipsum dolor sit amet, consectetur adipiscing elit.Tempor nibh
        </Typography>
        <Typography variant="h5" gutterBottom component="div">
          eget pharetra ac bibendum elit.
        </Typography>
        <Button
          sx={{
            margin: '2% 0',
            borderRadius: '5px',
            backgroundColor: '#4252FA',
          }}
        >
          Contact Us
        </Button>
      </Box>
      <ContainerCom fixed>
        <Grid container spacing={2}>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/Rectangle109.png" alt="" />
          </Grid>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Scalling
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              If plaque and tartar is left on the teeth, it provides the right
              conditions for bacteria to thrive. The bacteria irritate the gums,
              which means that they bleed more easily. if you are brushing your
              teeth, or eating, and sometimes your gums may bleed a bit.
            </Typography>
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Teeth Whitening
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              We can help you choose a whitening procedure that would be more
              effective for you.we may suggest a procedure that can be done in
              our office or we might even offer and provide you with several
              types of products that can be safely used at home to achieve
              stunning results.
            </Typography>
          </Grid>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/2.png" alt="" />
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/Rectangle109.png" alt="" />
          </Grid>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Desensitization
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              Teeth can be sensitive to a number of things including hot or
              cold, touch, or sweets. When the gums recede the root is exposed
              and under certain conditions may become sensitive. Desensitization
              uses techniques to protect the tooth root from these stimuli.{' '}
            </Typography>
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Sealants
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              Sealants are a thin, plastic coating painted on the chewing
              surfaces of teeth -- usually the back teeth (the premolars, and
              molars) -- to prevent tooth decay. The painted on liquid sealant
              quickly bonds into the depressions and grooves of the teeth
              forming a protective shield over the enamel of each tooth, protect
              the teeth from decay.
            </Typography>
          </Grid>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/Rectangle109.png" alt="" />
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/Rectangle109.png" alt="" />
          </Grid>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Fluoride Treatment
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              Tooth decay is caused by acid-producing bacteria that collect
              around the teeth and gingivae (gums) in a sticky, clear film
              called “plaque.” Typically, it is applied with a cotton swab or
              brush, or it is used as a rinse or placed in a tray that is held
              in the mouth for several minutes.
            </Typography>
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid
            item
            xs={12}
            md={7}
            sx={{ color: '#A3B5C4', fontWeight: '900' }}
          >
            <Typography variant="h2" gutterBottom component="div">
              Oral Cancer
            </Typography>
            <Typography
              variant="body1"
              gutterBottom
              component="div"
              sx={{ width: '60%' }}
            >
              Detecting the disease in the early stages is key to the survival
              rate. Thousands of new cases of oral cancer are diagnosed in
              Canada each year; the five-year survival rate of all oral cancer
              cases is about 50 per cent. Some estimates suggest that screening
              could detect as many as 80 per cent of new cases.
            </Typography>
          </Grid>
          <Grid item xs={12} md={5}>
            <ImgServis src="/images/aboutUs/Rectangle109.png" alt="" />
          </Grid>
        </Grid>
      </ContainerCom>
    </div>
  );
};
const ImgServis = styled.img`
  width: 100%;
  margin-top:-1% ;
`;

const ContainerCom = styled(Container)`
  line-height: 15;

`;

const ImgServises = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-start;
  justify-content: flex-start;
  align-items: flex-start;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;
const ImgServisesR = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-end;
  justify-content: flex-end;
  align-items: flex-end;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;

const BgBannerCenter = styled(Box)`
  background-image: url('/images/homePage/BgBannerCenter.png');
  background-size: cover;
  height: 368px;
  text-align: center;
  margin-bottom: 50px;
`;

const TypogerapyOnBanner = styled(Typography)`
  color: #fff;
  justify-content: center;
  display: flex;
  align-items: center;
  padding-top: 10%;
`;
const GoogleBox = styled(Typography)`
  margin-bottom: 50px;
  margin-top: 30px;
  border-bottom: 2px solid #000;
  width: fit-content;
`;
const BoxContentRevies = styled(Box)`
  background: #ffffff;
  box-shadow: 0px 0px 30px rgba(181, 181, 181, 0.25);
  border-radius: 25px;
  padding: 30px;
  a {
    color: #4060ff;
  }
`;

export const getStaticProps = async ({ locale }: HomeProps) => {
  return {
    props: {
      locale,
      ...(await serverSideTranslations(locale, ['common'], i18nConfig)),
    },
  };
};

export default Home;
