import { useTranslation, i18n } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppDispatch } from 'redux/store';
import Head from 'next/head';

// constants

// Components
import Button from 'components/Basic/Button';
import Container from 'layout/Container';
import Table from 'components/Basic/Table';
import { appSlice } from 'redux/slices';

import { useRouter } from 'next/router';
import i18nConfig from '../../i18n';
import Image from 'next/image';
import {
  Box,
  TextField,
  Grid,
  Typography,
  useMediaQuery,
  useTheme,
  Rating,
  Stack,
} from '@mui/material';
import Link from 'components/Basic/Link';
import { useCallback, useMemo, useState, useEffect } from 'react';
import axios from 'axios';
import CardsSwiper from 'components/Templates/CardsSwiper';
import 'keen-slider/keen-slider.min.css';
import { decimalEmitter } from 'consts/decimal';
import BannerContactUs from 'components/Basic/Banner/BannerContactus';
import VideoModal from 'components/Basic/videoModal/VideoModal';
import Carousels from 'components/Molecules/Card/card';
import styled from '@emotion/styled';
import Carousel from 'react-multi-carousel';

type HomeProps = {
  locale: string;
};

const ContactUS = () => {
  const { t } = useTranslation('common');
  const [priceCur, setPriceCur] = useState('irt');
  const router = useRouter();
  const matches = useMediaQuery((theme) => theme.breakpoints.up('lg'), {
    noSsr: true,
  });

  const ultraLarge = useMediaQuery('(min-width:3000px)', {
    noSsr: true,
  });

  // test
  return (
    <div>
      <Head>
        <title>Dental | Contact US</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* table section Banner */}

      <Box component="div">
        <BannerContactUs />
        <Box
          sx={{
            height: '560px',
            position: 'absolute',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'flex-start',
            flexDirection: 'column',
            left: 0,
            right: 0,
            margin: '0 55px',
            top: '2vh',
          }}
        >
          <Typography
            variant="h3"
            sx={{
              color: '#fff',
              fontWeight:'700',
              marginBottom:'50px'
            }}
            gutterBottom
            component="div"

          >
            Contact Us
          </Typography>
          

          <Button children={'Contact Us'} />
        </Box>
      </Box>
      <Container sx={{ marginTop: { xs: '10vh', md: '72vh' } }}>
        <Grid
          sx={{ alignItems: 'center', marginBottom: '100px' }}
          container
          spacing={2}
        >
          <Grid item xs={12} md={6}>
            <Grid>
              <Typography
                sx={{
                  marginBottom: '-8%',
                  color: '#DCDCDC',
                  fontWeight: '900',
                }}
                variant="h1"
                gutterBottom
                component="div"
              >
                Contact
              </Typography>
              <Typography
                sx={{ color: '#476B8A' ,fontWeight:'700'}}
                variant="h3"
                gutterBottom
                component="div"
              >
                Form
              </Typography>
            </Grid>
            <Typography variant="body1" gutterBottom component="div">
            You can keep in touch with us and ask all your questions. we will respond you as soon as possible.
            </Typography>
          </Grid>
          <GridMixPic item xs={12} md={6}>
          <FormGrid>
              <LabelInput>
              Full Name
                <InputForm type="text" name="name" />
              </LabelInput>
              <LabelInput>
              Email Address
                <InputForm type="mail" name="Emaile" />
              </LabelInput>
              <LabelInput>
              Phone Number
                <InputForm type="tel" name="PhoneNumber" />
              </LabelInput>
              <LabelInput>
              Message
              <TextareaForm/>
              </LabelInput>
              <ButtonDiv >
              <SubmitInput type="submit" value="Submit" />
              </ButtonDiv>
              
            </FormGrid>
          </GridMixPic>
        </Grid>

        <Grid sx={{ marginBottom:'20px'}} container spacing={2}>
          <Grid item md={12} xs={12} lg={12} sx={{ textAlign: 'center' }}>
            <Typography
              sx={{
                marginBottom: '-50px',
                color: '#DCDCDC',
                fontWeight: '900',
              }}
              variant="h1"
              gutterBottom
              component="div"
            >
              Contact
            </Typography>
            <Typography
              sx={{ color: '#476B8A',fontWeight:'700' }}
              variant="h3"
              gutterBottom
              component="div"
            >
              Our Clinic Contact Information
            </Typography>
          </Grid>
        </Grid>

        <Grid sx={{alignItems:'center', marginBottom:'100px'}} container spacing={2}>
          <Grid item md={6} lg={6} xs={12}>
          <iframe
              title="map"
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d809.69758998853!2d51.415313829277395!3d35.73137399876139!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3f8e014eb0073efb%3A0x7d59079f25f6d85a!2sMammut!5e0!3m2!1sen!2s!4v1587801898468!5m2!1sen!2s"
              width="100%"
              style={{ zIndex: '1' }}
              height="450px"
              frameborder="0"
            ></iframe>
          </Grid>
          <Grid item md={6} lg={6} xs={12}>
            <Grid>
              <Typography
                sx={{ marginBottom: '10px',fontWeight:'700'}}
                variant="h6"
                gutterBottom
                component="div"
              >
                Hours
              </Typography>
              <Typography variant="body2" gutterBottom>
                Mon-Thur : 8am - 5pm
              </Typography>
              <Typography variant="body2" gutterBottom>
                Friday : 8am - 5pm
              </Typography>
              <Typography variant="body2" gutterBottom>
                Sat : With Appointment
              </Typography>
            </Grid>
            <Grid>
              <Typography
                sx={{ marginBottom: '10px', marginTop:'10%' ,fontWeight:'700'}}
                variant="h6"
                gutterBottom
                component="div"
              >
                Phone Number
              </Typography>
              <Typography variant="body2" gutterBottom>
                <a href="#">(416) 746-0005</a>
              </Typography>
              <Typography variant="body2" gutterBottom>
                <a href="#">(647) 620-5444</a>
              </Typography>
            </Grid>
            <Grid>
              <Typography
                sx={{ marginBottom: '10px', marginTop:'10%' ,fontWeight:'700'}}
                variant="h6"
                gutterBottom
                component="div"
              >
                Address
              </Typography>
              <Typography variant="body2" gutterBottom>
                <a href="#">
                  3212 Weston Road, North York,
                  <br />
                  M9M 2T7 Ontario, Canada
                </a>
              </Typography>
              <Typography variant="body2" gutterBottom>
                <a href="#">(Get Direction</a>
              </Typography>
            </Grid>
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};



const LabelInput =styled.label`
color:#323232

`;

const ButtonDiv = styled.div`
font-weight:700 ;
text-align:center ;
`;

const InputForm =styled.input`
width:100% ;
padding:10px ;
border: 1px solid #A6A6A6 ;
border-radius:5px ;
position:block ;
min-height:50px ;
margin: 6px 0 20px 0;
:focus { 
    outline: none !important;
    border-color: #6875F7;
    
}`;

const TextareaForm = styled.textarea`
  width:100% ;
border: 1px solid #A6A6A6 ;
border-radius:5px ;
position:block ;
min-height:112px ;
margin: 6px 0 20px 0;
padding:10px ;
:focus { 
    outline: none !important;
    border-color: #6875F7;
    
}
`;
const SubmitInput = styled.input`
font-family:AirbnbCerealApp  !important;
font-weight:700 ;
background: #6875F7;
border-radius: 5px;
height:45px ;
min-width:112px ;
border:none ;
color:#fff ;
text-align:center ;
cursor:pointer;
:hover{
  background: #4F5FFF;
border-radius: 5px;

}`
const FormGrid = styled(Grid)`
  background: #ffffff;
  box-shadow: 0px 0px 17px rgba(155, 155, 155, 0.25);
  border-radius: 5px;
  padding: 25px;
`;

const TypogerapyForm = styled(Typography)`
  color: #000;
  margin-top: 20px;
`;
const TextFieldInputForm = styled(TextField)`
  .css-ltr-av9tmb-MuiFormLabel-root-MuiInputLabel-root {
    color: #a6a6a6;
  }
  .css-ltr-1ikgno3-MuiOutlinedInput-notchedOutline {
    border-color: #a6a6a6;
  }
`;
const TextFieldInputFormMessege = styled(TextField)`
  .css-ltr-av9tmb-MuiFormLabel-root-MuiInputLabel-root {
    color: #a6a6a6;
  }
  .css-ltr-1ikgno3-MuiOutlinedInput-notchedOutline {
    border-color: #a6a6a6;
  }
  .css-ltr-17cvodc-MuiInputBase-input-MuiOutlinedInput-input {
    min-height: 5rem !important ;
  }
`;

const PhoneBox = styled(Grid)`
  border-left: 1px solid #6d86ff;
  border-right: 1px solid #6d86ff;
`;

const ContainerCom = styled(Container)`
  box-shadow: 0px 0px 16px rgb(197 197 197 / 25%);
  border-radius: 52px;
  width: 80%;
  background-color: #fff;
  border: 1px solid #817e84;
  min-height: 272px;
`;

const ImgServises = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-start;
  justify-content: flex-start;
  align-items: flex-start;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;
const ImgServisesR = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-end;
  justify-content: flex-end;
  align-items: flex-end;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;

const BgBannerCenter = styled(Box)`
  background-image: url('/images/homePage/BgBannerCenter.png');
  background-size: cover;
  height: 406px;
  text-align: center;
  margin-bottom: 20%;
`;

const GridPics = styled(Grid)`
  background-image: url('/images/homePage/p1.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
`;
const GridPicTo = styled(Grid)`
  background-image: url('/images/homePage/p2.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
`;
const GridPicT = styled(Grid)`
  background-image: url('/images/homePage/p3.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
`;

const TypogerapyOnBanner = styled(Typography)`
  color: #fff;
  justify-content: center;
  display: flex;
  align-items: center;
  padding-top: 10%;
`;
const GoogleBox = styled(Typography)`
  margin-bottom: 50px;
  margin-top: 30px;
  border-bottom: 2px solid #000;
  width: fit-content;
`;
const BoxContentRevies = styled(Box)`
  background: #ffffff;
  box-shadow: 0px 0px 30px rgba(181, 181, 181, 0.25);
  border-radius: 25px;
  padding: 30px;
  a {
    color: #4060ff;
  }
`;
const GridMixPic = styled(Grid)`
  z-index: 1;
  img {
    margin-top: -150px;
    width: 100%;
  }
`;

const GridIconContent = styled(Grid)`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  img {
    margin-bottom: 15px;
  }
`;
const GridAboutUsBanner = styled(Grid)`
  img {
    width: 100%;
  }
`;
export const getStaticProps = async ({ locale }: HomeProps) => {
  return {
    props: {
      locale,
      ...(await serverSideTranslations(locale, ['common'], i18nConfig)),
    },
  };
};

export default ContactUS;
