import { useTranslation, i18n } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppDispatch } from 'redux/store';
import Head from 'next/head';

// constants

// Components
import Button from 'components/Basic/Button';
import Container from 'layout/Container';
import Table from 'components/Basic/Table';
import { appSlice } from 'redux/slices';

import { useRouter } from 'next/router';
import i18nConfig from '../../i18n';
import Image from 'next/image';
import {
  Box,
  TextField,
  Grid,
  Typography,
  useMediaQuery,
  useTheme,
  Rating,
  Stack,
} from '@mui/material';
import Link from 'components/Basic/Link';
import { useCallback, useMemo, useState, useEffect } from 'react';
import axios from 'axios';
import CardsSwiper from 'components/Templates/CardsSwiper';
import 'keen-slider/keen-slider.min.css';
import { decimalEmitter } from 'consts/decimal';
import BannerGeneral from 'components/Basic/Banner/BannerGeneral';
import VideoModal from 'components/Basic/videoModal/VideoModal';
import Carousels from 'components/Molecules/Card/card';
import styled from '@emotion/styled';
import Carousel from 'react-multi-carousel';

type HomeProps = {
  locale: string;
};

const General = () => {
  const { t } = useTranslation('common');
  const [priceCur, setPriceCur] = useState('irt');
  const router = useRouter();
  const matches = useMediaQuery((theme) => theme.breakpoints.up('lg'), {
    noSsr: true,
  });

  const ultraLarge = useMediaQuery('(min-width:3000px)', {
    noSsr: true,
  });

  // test
  return (
    <div>
      <Head>
        <title>Dental | General Dentistry</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* table section Banner */}

      <Box component="div">
        <BannerGeneral />
        <Box
          sx={{
            height: '560px',
            position: 'absolute',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'flex-start',
            flexDirection: 'column',
            left: 0,
            right: 0,
            margin: '0 55px',
            top: '2vh',
          }}
        >
          <Typography
            variant="h3"
            sx={{
              color: '#fff',
              fontWeight:'700'
            }}
            gutterBottom
            component="div"
          >
            General Dentistry
          </Typography>
        </Box>
      </Box>
      <Container sx={{ marginTop: { xs: '10vh', md: '72vh' } }}>
        <Grid
          sx={{ alignItems: 'center', marginBottom: '100px' }}
          container
          spacing={2}
        >
          <Grid item xs={12} md={6}>
            <Grid>
              <Typography
                sx={{
                  marginBottom: '-8%',
                  color: '#DCDCDC',
                  fontWeight: '900',
                }}
                variant="h1"
                gutterBottom
                component="div"
              >
                About
              </Typography>
              <Typography
                sx={{ color: '#476B8A',fontWeight:'700' }}
                variant="h3"
                gutterBottom
                component="div"
              >
                General Dentistry
              </Typography>
            </Grid>
            <Typography variant="body1" gutterBottom component="div">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ac
              tincidunt ultricies vitae cras. Lorem velit porta viverra
              facilisis lacus hac. Sed dignissim diam pretium tellus. In turpis
              praesent felis sed iaculis. Mi id proin risus massa est felis
              quam.facilisis lacus hac. Sed dignissim diam pretium tellus. In
              turpis praesent felis sed iaculis. Mi id proin risus massa est
              felis quam.
            </Typography>
          </Grid>
          <GridMixPic item xs={12} md={6}>
            <img src="/images/GeneralPage/MainPic.png" alt="" />
          </GridMixPic>
        </Grid>
        <Grid container spacing={2}>
          <Grid item xs={12} md={12}>
            <BgBannerCenter>
              <Grid sx={{ paddingTop: '100px' }} container spacing={2}>
                <GridAboutUsBanner item md={6} xs={12}>
                  <img src="/images/GeneralPage/picBanner.png" alt="pic" />
                </GridAboutUsBanner>
                <Grid sx={{ textAlign: 'left' }} item md={6} xs={12}>
                  <Typography
                    sx={{ color: '#FFF' }}
                    variant="h3"
                    gutterBottom
                    component="div"
                  >
                    Lorem ipsum dolor sit amet, consectetur adipiscing elit.
                  </Typography>

                  <Button
                    sx={{
                      color: '#4060FF',
                      backgroundColor: '#fff',
                      minWidth: '160px',
                      minHeight: '45px',
                    }}
                    children={'contact US'}
                  />
                </Grid>
              </Grid>
            </BgBannerCenter>
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/GeneralPage/toothextraction.png" alt="" />
          </Grid>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Tooth Extraction
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              our primary goal is to always save your tooth and we will make
              every effort to restore and repair your teeth but sometimes due to
              extreme conditions it is an unavoidable reality. Prior to any
              extraction, we will discuss the your options with you and make
              sure your medical history and medications are fully reviewed in
              advance.
            </Typographycontent>
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px' }} container spacing={2}>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Cavity prevention and treatment
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Regular proper brushing and flossing are essential in maintaining
              your dental health; however, sometimes despite your efforts to
              keep your teeth healthy cavities occur due to several reasons such
              as poor nutrition, smoking, alcohol consumption, and diabetes.
              Depending on you the tooth condition, we might suggest a range of
              treatments such as filling,crown and root canal.
            </Typographycontent>
          </Grid>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/GeneralPage/Cavity.png" alt="" />
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px',marginBottom:'100px' }} container spacing={2}>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/GeneralPage/rootcanal.png" alt="" />
          </Grid>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Root Canal
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Teeth can become damaged and infected due to severe decay,
              repeated dental procedures, cracks in the tooth or trauma to the
              face. Constant pain, swelling and tenderness of the gums,
              prolonged sensitivity to heat or cold and discoloration of the
              tooth are signs that one may need a root canal. A root canal is a
              procedure done to treat and save a tooth that is damaged, infected
              or badly decayed. The treatment involves the removal of the
              inflamed or infected nerves and pulp inside the tooth. That area
              inside the tooth is then cleaned, disinfected and sealed. After
              restoration, a root-canaled tooth continues to function like any
              other healthy tooth.
            </Typographycontent>

          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

const TypographyTittle = styled(Typography)`
  color: #476b8a;
  font-weight:700 ;
`;
const Typographycontent = styled(Typography)`
  line-height: 2.3;
  color:#343434 ;
`;
const GridMixPic = styled(Grid)`
  z-index: 1;
  img {
    width: 100%;
  }
`;
const BgBannerCenter = styled(Box)`
  background-image: url('/images/homePage/BgBannerCenter.png');
  background-size: cover;
  height: 406px;
  text-align: center;
  margin-bottom: 20%;
`;

const GridAboutUsBanner = styled(Grid)`
  img {
    width: 90%;
  }
`;
export const getStaticProps = async ({ locale }: HomeProps) => {
  return {
    props: {
      locale,
      ...(await serverSideTranslations(locale, ['common'], i18nConfig)),
    },
  };
};

export default General;
