import { useTranslation, i18n } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppDispatch } from 'redux/store';
import Head from 'next/head';

// constants

// Components
import Button from 'components/Basic/Button';
import Container from 'layout/Container';
import Table from 'components/Basic/Table';
import { appSlice } from 'redux/slices';

import { useRouter } from 'next/router';
import i18nConfig from '../../i18n';
import Image from 'next/image';
import {
  Box,
  TextField,
  Grid,
  Typography,
  useMediaQuery,
  useTheme,
  Rating,
  Stack,
} from '@mui/material';
import Link from 'components/Basic/Link';
import { useCallback, useMemo, useState, useEffect } from 'react';
import axios from 'axios';
import CardsSwiper from 'components/Templates/CardsSwiper';
import 'keen-slider/keen-slider.min.css';
import { decimalEmitter } from 'consts/decimal';
import BannerHygiene from 'components/Basic/Banner/BannerHygiene';
import VideoModal from 'components/Basic/videoModal/VideoModal';
import Carousels from 'components/Molecules/Card/card';
import styled from '@emotion/styled';
import Carousel from 'react-multi-carousel';

type HomeProps = {
  locale: string;
};

const hygiene = () => {
  const { t } = useTranslation('common');
  const [priceCur, setPriceCur] = useState('irt');
  const router = useRouter();
  const matches = useMediaQuery((theme) => theme.breakpoints.up('lg'), {
    noSsr: true,
  });

  const ultraLarge = useMediaQuery('(min-width:3000px)', {
    noSsr: true,
  });

  // test
  return (
    <div>
      <Head>
        <title>Dental | hygiene page</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* table section Banner */}

      <Box component="div">
        <BannerHygiene />
        <Box
          sx={{
            height: '560px',
            position: 'absolute',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'flex-start',
            flexDirection: 'column',
            left: 0,
            right: 0,
            margin: '0 55px',
            top: '2vh',
          }}
        >
          <Typography
            variant="h3"
            sx={{
              color: '#fff',
              fontWeight:'700'
            }}
            gutterBottom
            component="div"
          >
            Dental Hygiene
          </Typography>
        </Box>
      </Box>
      <Container sx={{ marginTop: { xs: '10vh', md: '72vh' } }}>
        <Grid
          sx={{ alignItems: 'center', marginBottom: '100px' }}
          container
          spacing={2}
        >
          <Grid item xs={12} md={6}>
            <Grid>
              <Typography
                sx={{
                  marginBottom: '-8%',
                  color: '#DCDCDC',
                  fontWeight: '900',
                }}
                variant="h1"
                gutterBottom
              >
                About
              </Typography>
              <Typography
                sx={{ color: '#476B8A',
                fontWeight:'700'
              }}
                variant="h3"
                gutterBottom
                component="div"
              >
                Dental Hygiene
              </Typography>
            </Grid>
            <Typography variant="body1" gutterBottom component="div">
              Lorem ipsum dolor sit amet, consectetur adipiscing elit. Ac
              tincidunt ultricies vitae cras. Lorem velit porta viverra
              facilisis lacus hac. Sed dignissim diam pretium tellus. In turpis
              praesent felis sed iaculis. Mi id proin risus massa est felis
              quam.facilisis lacus hac. Sed dignissim diam pretium tellus. In
              turpis praesent felis sed iaculis. Mi id proin risus massa est
              felis quam.
            </Typography>
          </Grid>
          <GridMixPic item xs={12} md={6}>
            <img src="/images/HygienePage/minPic.png" alt="" />
          </GridMixPic>
        </Grid>
        <Grid container spacing={2}>
          <Grid item xs={12} md={12}>
            <BgBannerCenter>
              <Grid sx={{ paddingTop: '100px' }} container spacing={2}>
                <GridAboutUsBanner item md={6} xs={12}>
                  <img src="/images/HygienePage/BannerCenter.png" alt="pic" />
                </GridAboutUsBanner>
                <Grid sx={{ textAlign: 'left' }} item md={6} xs={12}>
                  <Typography
                    sx={{ color: '#FFF', fontWeight:'700' }}
                    variant="h4"
                    gutterBottom
                    component="div"
                  >
                    Don’t Worry About Your Payment.
                  </Typography>
                  <Typography
                    sx={{ color: '#FFF', fontWeight:'700' }}
                    variant="h6"
                    gutterBottom
                    component="div"
                  >
                    You Can Pay With Credit Cards, Cash Or Personla Cheques.
                  </Typography>
                  <Button
                    sx={{
                      color: '#4060FF',
                      backgroundColor: '#fff',
                      minWidth: '160px',
                      minHeight: '45px',
                    }}
                    children={'contact US'}
                  />
                </Grid>
              </Grid>
            </BgBannerCenter>
          </Grid>
        </Grid>
        <Grid container spacing={2}>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/scalling.png" alt="" />
          </Grid>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle  variant="h3" gutterBottom component="div">
              Scalling
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              If plaque and tartar is left on the teeth, it provides the right
              conditions for bacteria to thrive. The bacteria irritate the gums,
              which means that they bleed more easily. You may notice this if
              you are brushing your teeth, or eating, and sometimes your gums
              may bleed a bit. This is the early stage of gum disease called
              gingivitis. If you have gingivitis, we will clean your teeth by
              scaling and polishing them. We may also recommend an antiseptic
              mouthwash containing Chlorhexidine, and show you how to brush and
              floss your teeth effectively. Most adults have some degree of gum
              disease. If gingivitis not treated and nothing is done about it,
              the inflammation will work its way down towards the foundations of
              the tooth causing a “periodontal pocket”. Again, within the
              confines of the pocket, the conditions are such that the bacteria
              can have a right old party, and cause more damage. Through out the
              scaling procedure we will remove the built-up tartar completely,
              and you will feel silky smooth surface on your teeth in the end.
            </Typographycontent>
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px' }} container spacing={2}>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Whitening
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Everybody loves a bright white smile, and there are a variety of
              products and procedures available to help you improve the look of
              yours.
              <br />
              <br />
              Many people are satisfied with the sparkle they get from brushing
              twice daily with a fluoride-containing toothpaste, cleaning
              between their teeth once a day and the regular cleanings at your
              dentist’s office. If you decide you would like to go beyond this
              to make your smile look brighter, we can help you by offering you
              different affordable and effective approaches. We can help you
              choose a whitening procedure that would be more effective for you.
              If you are a candidate for bleaching, we may suggest a procedure
              that can be done in our office or we might even offer and provide
              you with several types of products that can be safely used at home
              to achieve stunning results.
            </Typographycontent>
          </Grid>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/whitening.png" alt="" />
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px' }} container spacing={2}>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/Desensitization.png" alt="" />
          </Grid>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Desensitization
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Teeth can be sensitive to a number of things including hot or
              cold, touch, or sweets. These can generally be grouped into a
              hypersensitive situation of the tooth root. When the gums recede
              the root is exposed and under certain conditions may become
              sensitive. Desensitization uses techniques to protect the tooth
              root from these stimuli.
            </Typographycontent>
            <Typographycontent variant="subtitle1" gutterBottom>
              Our office has new ‘needle-less” procedures that apply a topical
              anesthetic to the teeth that may reduce or eliminate tooth
              sensitivity during scaling and root planing procedures. You can
              decrease tooth sensitivity with:
            </Typographycontent>
            <Typographycontent variant="subtitle1" gutterBottom>
              <ul>
                <li>
                  Brush gently with a soft toothbrush twice/day using a low
                  abrasion desensitizing toothpaste
                </li>
                <li>
                  {' '}
                  Having professional tooth cleaning, oral hygiene instructions
                  and fluoride treatments.
                </li>
                <li>
                  Avoid highly acidic foods like citrus or soda pop that can
                  work against the sensitivity toothpaste
                </li>
              </ul>
            </Typographycontent>
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px' }} container spacing={2}>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Sealants
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Although thorough brushing and flossing can remove food particles
              and plaque from smooth surfaces of teeth, they cannot always get
              into all the nooks and crannies of the back teeth to remove the
              food and plaque. Sealants protect these vulnerable areas from
              tooth decay by "sealing out" plaque and food.
              <br />
              <br />
              Sealants are a thin, plastic coating painted on the chewing
              surfaces of teeth -- usually the back teeth (the premolars, and
              molars) -- to prevent tooth decay. The painted on liquid sealant
              quickly bonds into the depressions and grooves of the teeth
              forming a protective shield over the enamel of each tooth.
              Sealants can protect the teeth from decay for up to 10 years, but
              they need to be checked for chipping or wearing at regular dental
              check-ups and can be replaced if necessary
            </Typographycontent>
          </Grid>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/sealants.png" alt="" />
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px' }} container spacing={2}>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/flouridetreatment.png" alt="" />
          </Grid>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
              Flouride treatment
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
              Tooth decay is caused by acid-producing bacteria that collect
              around the teeth and gingivae (gums) in a sticky, clear film
              called “plaque.” Brushing twice a day and cleaning between teeth
              with floss or another type of inter- dental cleaner help remove
              plaque. Regular dental examinations and cleanings also are
              important for keeping teeth healthy.
            </Typographycontent>
            <Typographycontent variant="subtitle1" gutterBottom>
              If you, or a family member, are at a moderate-to- high risk of
              developing caries, our professional fluo-ride treatment can help.
            </Typographycontent>
            <Typographycontent variant="subtitle1" gutterBottom>
              Professional fluoride treatments generally take just a few
              minutes. The fluoride may be in the form of a solution, gel, foam
              or varnish. Typically, it is applied with a cotton swab or brush,
              or it is used as a rinse or placed in a tray that is held in the
              mouth for several minutes.
              <br />
              Depending on your oral health status, fluoride treatments may be
              recommended every three, six or 12 months.
            </Typographycontent>
          </Grid>
        </Grid>
        <Grid sx={{ marginTop: '70px',marginBottom:'100px' }} container spacing={2}>
          <Grid item md={8} lg={8} xs={12}>
            <TypographyTittle variant="h3" gutterBottom component="div">
            Oral cancer screening
            </TypographyTittle>
            <Typographycontent variant="subtitle1" gutterBottom>
            Oral cancer screening (OCS) may be the best way to detect oral cancer early, and dental hygienists have an important role. They screen for oral cancer as part of every dental hygiene appointment, regardless of age, and educate clients about risk factors and how to detect potential problems. Detecting the disease in the early stages is key to the survival rate. Thousands of new cases of oral cancer are diagnosed in Canada each year; the five-year survival rate of all oral cancer cases is about 50 per cent. Some estimates suggest that screening could detect as many as 80 per cent of new cases.


            </Typographycontent>
          </Grid>
          <Grid item md={4} lg={4} xs={12}>
            <img src="/images/HygienePage/oralcancerscreeni.png" alt="" />
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

const TypographyTittle = styled(Typography)`
  color: #476b8a;
  font-weight:700 ;
`;
const Typographycontent = styled(Typography)`
  line-height: 2.3;
  color:#343434 ;
`;
const GridMixPic = styled(Grid)`
  z-index: 1;
  img {
    width: 100%;
  }
`;
const BgBannerCenter = styled(Box)`
  background-image: url('/images/homePage/BgBannerCenter.png');
  background-size: cover;
  height: 406px;
  text-align: center;
  margin-bottom: 20%;
`;


const GridAboutUsBanner = styled(Grid)`
  img {
    width: 90%;
  }
`;
export const getStaticProps = async ({ locale }: HomeProps) => {
  return {
    props: {
      locale,
      ...(await serverSideTranslations(locale, ['common'], i18nConfig)),
    },
  };
};

export default hygiene;
