import { useTranslation, i18n } from 'next-i18next';
import { serverSideTranslations } from 'next-i18next/serverSideTranslations';
import { useAppDispatch } from 'redux/store';
import Head from 'next/head';

// constants

// Components
import Button from 'components/Basic/Button';
import Container from 'layout/Container';
import Table from 'components/Basic/Table';
import { appSlice } from 'redux/slices';

import { useRouter } from 'next/router';
import i18nConfig from '../../i18n';
import Image from 'next/image';
import {
  Box,
  TextField,
  Grid,
  Typography,
  useMediaQuery,
  useTheme,
  Rating,
  Stack,
} from '@mui/material';
import Link from 'components/Basic/Link';
import { useCallback, useMemo, useState, useEffect } from 'react';
import axios from 'axios';
import CardsSwiper from 'components/Templates/CardsSwiper';
import 'keen-slider/keen-slider.min.css';
import { decimalEmitter } from 'consts/decimal';
import Banner from 'components/Basic/Banner/Banner';
import VideoModal from 'components/Basic/videoModal/VideoModal';
import Carousels from 'components/Molecules/Card/card';
import styled from '@emotion/styled';
import Carousel from 'react-multi-carousel';
import ArrowForwardIosIcon from '@mui/icons-material/ArrowForwardIos';

type HomeProps = {
  locale: string;
};

const Home = () => {
  const { t } = useTranslation('common');
  const [priceCur, setPriceCur] = useState('irt');
  const router = useRouter();
  const matches = useMediaQuery((theme) => theme.breakpoints.up('lg'), {
    noSsr: true,
  });

  const ultraLarge = useMediaQuery('(min-width:3000px)', {
    noSsr: true,
  });

  // test
  return (
    <div>
      <Head>
        <title>Dental</title>
        {/* <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" /> */}
      </Head>
      {/* table section Banner */}

      <Box component="div">
        <Banner />
        <Box
          sx={{
            height: '560px',
            position: 'absolute',
            display: 'flex',
            justifyContent: 'center',
            alignItems: 'flex-start',
            flexDirection: 'column',
            left: 0,
            right: 0,
            margin: '0 55px',
            top: '2vh',
          }}
        >
          <Typography
            variant="h3"
            sx={{
              color: '#fff',
              fontWeight: '700',
            }}
            gutterBottom
            component="div"
          >
            The Days Of Covering
          </Typography>
          <Typography
            sx={{
              color: '#fff',
              fontWeight: '700',
            }}
            variant="h3"
            gutterBottom
            component="div"
          >
            Your Smile Are Over
          </Typography>
          <Typography
            sx={{
              color: '#fff',
              fontWeight: '700',
              marginBottom: '50px',
            }}
            variant="h5"
            gutterBottom
            component="div"
          >
            Trust A&E Dental Services
          </Typography>

          <Button children={'Contact Us'} />
        </Box>
      </Box>
      <Container sx={{ marginTop: { xs: '10vh', md: '72vh' } }}>
        <Grid
          sx={{ alignItems: 'center', marginBottom: '100px' }}
          container
          spacing={2}
        >
          <Grid item xs={12} md={6}>
            <Grid>
              <RubikTiitle
                sx={{
                  marginBottom: '-8%',
                  color: '#DCDCDC',
                }}
                variant="h1"
                gutterBottom
              >
                Welcome
              </RubikTiitle>
              <Typography
                sx={{ color: '#476B8A', fontWeight: '700' }}
                variant="h3"
                gutterBottom
                component="div"
              >
                To A&E Clinic
              </Typography>
            </Grid>
            <Typography
              sx={{ color: '#343434' }}
              variant="body1"
              gutterBottom
              component="div"
            >
              With years of professional experience and extensive insight into
              preventative measures for better dental health, we offer general
              and cosmetic dental services to the community with utmost care and
              affordable rates. Like many dental health practitioners, we firmly
              believe that preventative care is a key component of obtaining and
              maintaining good dental health.
            </Typography>
          </Grid>
          <GridMixPic item xs={12} md={6}>
            <img src="/images/homePage/mix.png" alt="" />
          </GridMixPic>
        </Grid>
        <Grid container spacing={2}>
          <Grid item xs={12} md={12}>
            <BgBannerCenter>
              <Grid sx={{ paddingTop: '100px' }} container spacing={2}>
                <GridAboutUsBanner item md={6} xs={12}>
                  <img
                    src="/images/homePage/aboutus-homepage-top.png"
                    alt="pic"
                  />
                </GridAboutUsBanner>
                <Grid sx={{ textAlign: 'left' }} item md={6} xs={12}>
                  <Typography
                    sx={{ color: '#FFF', fontWeight: '700' }}
                    variant="h3"
                    gutterBottom
                    component="div"
                  >
                    Achieve The Best Oral Health Possible With Our Team.
                  </Typography>
                  <AbutusButton
                    sx={{
                      color: '#4060FF',
                      backgroundColor: '#fff',
                      minWidth: '160px',
                      minHeight: '45px',
                      fontWeight: '700',
                    }}
                    children={'about US'}
                  />
                </Grid>
              </Grid>
            </BgBannerCenter>
          </Grid>
          <SloganRow item xs={12} md={12}>
            <Grid sx={{ textAlign: 'center' }}>
              <Typography
                sx={{
                  marginBottom: '-50px',
                  color: '#DCDCDC',
                  fontWeight: '900',
                }}
                variant="h1"
                gutterBottom
                component="div"
              >
                Benefits
              </Typography>
              <Typography
                sx={{ color: '#476B8A', fontWeight: '700' }}
                variant="h3"
                gutterBottom
                component="div"
              >
                A&E
              </Typography>
            </Grid>
          </SloganRow>
        </Grid>

        <Grid container spacing={2}>
          <GridIconContent item xs={12} md={4}>
            <img src="/images/icon/homePage/1.png" alt="" />
            <Typography
              sx={{ color: '#476B8A', fontWeight: '700' }}
              variant="h5"
              gutterBottom
              component="div"
            >
              Healthier You
            </Typography>
            <Typography
              sx={{ color: '#343434' }}
              variant="subtitle1"
              gutterBottom
              component="div"
            >
              We work with you to help keep your mouth healthy, attain and
              maintain oral health, which in turn makes an important
              contribution to your overall health.
            </Typography>
          </GridIconContent>
          <GridIconContent item xs={12} md={4}>
            <img src="/images/icon/homePage/2.png" alt="" />
            <Typography
              sx={{ color: '#476B8A', fontWeight: '700' }}
              variant="h5"
              gutterBottom
              component="div"
            >
              Affodable
            </Typography>
            <Typography
              sx={{ color: '#343434' }}
              variant="subtitle1"
              gutterBottom
              component="div"
            >
              Not everyone has dental insurance. At A&E Dental Centre, you can
              expect to get professional, immaculate and personalized dental
              services at discounted rates.
            </Typography>
          </GridIconContent>
          <GridIconContent item xs={12} md={4}>
            <img src="/images/icon/homePage/3.png" alt="" />
            <Typography
              sx={{ color: '#476B8A', fontWeight: '700' }}
              variant="h5"
              gutterBottom
              component="div"
            >
              Convinient
            </Typography>
            <Typography
              sx={{ color: '#343434' }}
              variant="subtitle1"
              gutterBottom
              component="div"
            >
              We appreciate your daily busy schedules. We offer a relaxed
              environment where you do not feel rushed and are scheduled in a
              time that works for you.
            </Typography>
          </GridIconContent>
        </Grid>
        <SloganRow sx={{ marginTop: '100px' }} item xs={12} md={12}>
          <Grid sx={{ textAlign: 'center' }}>
            <Typography
              sx={{
                marginBottom: '-50px',
                color: '#DCDCDC',
                fontWeight: '900',
              }}
              variant="h1"
              gutterBottom
              component="div"
            >
              Services
            </Typography>
            <Typography
              sx={{ color: '#476B8A', fontWeight: '700' }}
              variant="h3"
              gutterBottom
              component="div"
            >
              We Will Give Many Reasons To Smile
            </Typography>
          </Grid>
        </SloganRow>
        <Grid container>
          <GridPics item xs={12} md={4}>
            <Typography variant="h4" gutterBottom component="div">
              General Dentistry
            </Typography>
          </GridPics>
          <GridPicTo item xs={12} md={4}>
            <Typography
              className="firstContentPicTo"
              variant="h4"
              gutterBottom
              component="div"
            >
              Dental Hygiene
            </Typography>
            <Grid className="secendContentPicTo">
              <div>
                <ArrowForwardIosIcon />
                <p variant="h5" gutterBottom component="div">
                  Dental Hygiene
                </p>
              </div>
              <div>
                <ArrowForwardIosIcon />
                <p variant="h5" gutterBottom component="div">
                  Dental Hygiene
                </p>
              </div>
            </Grid>
          </GridPicTo>
          <GridPicT item xs={12} md={4}>
            <Typography variant="h4" gutterBottom component="div">
              Cosmetic Dentistry
            </Typography>
          </GridPicT>
        </Grid>
        <Grid sx={{ marginTop: '100px' }} container spacing={2}>
          <Grid item xs={12} md={4}>
            <Box>
              <Typography
                sx={{
                  color: '#476B8A',
                  fontWeight: '700',
                }}
                variant="h4"
                gutterBottom
                component="div"
              >
                Our Happy Patients
              </Typography>
              <Stack spacing={1}>
                <Rating name="half-rating" defaultValue={2.5} precision={0.5} />
              </Stack>
              <GoogleBox>
                <a href="#">
                  <Typography variant="h6" gutterBottom component="div">
                    See More Google Reviews
                  </Typography>
                </a>
              </GoogleBox>
            </Box>
          </Grid>
          <Grid item xs={12} md={4}>
            <BoxContentRevies>
              <Typography
                sx={{ color: '#343434' }}
                variant="body1"
                gutterBottom
                component="div"
              >
                A&E Dental Centre is a well-organized and clean office. They
                helped me out to re-schedule my appointments many times and
                treated me with respect. It feels like home here
              </Typography>
              <a href="#">Mohammad Hassan, Etobicoke</a>
            </BoxContentRevies>
          </Grid>
          <Grid item xs={12} md={4}>
            <BoxContentRevies>
              <Typography
                sx={{ color: '#343434' }}
                variant="body1"
                gutterBottom
                component="div"
              >
                Although visits to the dentist are typically frightening, the
                friendly service makes it comfortable in here. A&E Dental Centre
                is my favourite dental office!
              </Typography>
              <a href="#">Shamsa Abdullahi, Etobicoke</a>
            </BoxContentRevies>
          </Grid>
        </Grid>
        <SloganRow container spacing={2}>
          <Grid
            item
            md={12}
            xs={12}
            lg={12}
            sx={{ textAlign: 'center', marginTop: '100px' }}
          >
            <Typography
              sx={{
                marginBottom: '-50px',
                color: '#DCDCDC',
                fontWeight: '900',
              }}
              variant="h1"
              gutterBottom
              component="div"
            >
              Contact
            </Typography>
            <Typography
              sx={{ color: '#476B8A', fontWeight: '700' }}
              variant="h3"
              gutterBottom
              component="div"
            >
              Our Clinic Contact Information
            </Typography>
          </Grid>
        </SloganRow>
        <Grid sx={{ alignItems: 'center', justifyContent:'space-around' }} container spacing={2}>
          <Grid item md={6} lg={6} xs={12}>
            <FormGrid>
              <LabelInput>
                Full Name
                <InputForm type="text" name="name" />
              </LabelInput>
              <LabelInput>
                Email Address
                <InputForm type="mail" name="Emaile" />
              </LabelInput>
              <LabelInput>
                Phone Number
                <InputForm type="tel" name="PhoneNumber" />
              </LabelInput>
              <LabelInput>
                Message
                <TextareaForm />
              </LabelInput>
              <ButtonDiv>
                <SubmitInput type="submit" value="Submit" />
              </ButtonDiv>
            </FormGrid>
          </Grid>
        </Grid>
        <Grid sx={{ alignItems: 'center',marginTop:'150px',marginBottom:'-9%'}} container spacing={6}>
          <Grid sx={{zIndex:'1'}} item md={4} lg={4} xs={12}>
          <GridContacUSDetail>
          <Typography
                sx={{
                  marginBottom: '10px',
                  fontWeight: '700',
                  color: '#323232',
                }}
                variant="h6"
                gutterBottom
                component="div"
              >
                Hours
              </Typography>
              <Typography
                sx={{ color: '#323232' }}
                variant="body2"
                gutterBottom
              >
                Mon-Thur : 8am - 5pm
              </Typography>
              <Typography
                sx={{ color: '#323232' }}
                variant="body2"
                gutterBottom
              >
                Friday : 8am - 5pm
              </Typography>
              <Typography
                sx={{ color: '#323232' }}
                variant="body2"
                gutterBottom
              >
                Sat : With Appointment
              </Typography>

            </GridContacUSDetail>
          </Grid>
          <Grid sx={{zIndex:'1'}} item md={4} lg={4} xs={12}>
          <GridContacUSDetail>
          <Typography
                sx={{
                  marginBottom: '10px',
                  marginTop: '10%',
                  fontWeight: '700',
                  color: '#323232',
                }}
                variant="h6"
                gutterBottom
                component="div"
              >
                Phone Number
              </Typography>
              <TypographyLink variant="body2" gutterBottom>
                <a href="tel:+1416746005:">(416) 746-0005</a>
              </TypographyLink>
              <TypographyLink variant="body2" gutterBottom>
                <a href="tel:+6476205444">(647) 620-5444</a>
              </TypographyLink>

            </GridContacUSDetail>
          </Grid>
          <Grid sx={{zIndex:'1'}} item md={4} lg={4} xs={12}>
          <GridContacUSDetail>
          <Typography
                sx={{
                  marginBottom: '10px',
                  marginTop: '10%',
                  fontWeight: '700',
                  color: '#323232',
                }}
                variant="h6"
                gutterBottom
                component="div"
              >
                Address
              </Typography>
              <Typography
                sx={{ color: '#323232' }}
                variant="body2"
                gutterBottom
              >
                3212 Weston Road, North York,
                <br />
                M9M 2T7 Ontario, Canada
              </Typography>
              <TypographyLink variant="body2" gutterBottom>
                <a href="#">Get Direction</a>
              </TypographyLink>

            </GridContacUSDetail>
          </Grid>
        </Grid>
        <Grid container>
          <Grid item xs={12}>
            <iframe
              src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d2882.6585489248055!2d-79.54212598458666!3d43.73841965493398!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x882b3067bf8b54b5%3A0xac418b6fe192298e!2sA%26E%20Dental%20Centre!5e0!3m2!1sen!2ssc!4v1653213963144!5m2!1sen!2ssc"
              width="100%"
              height="486"
              style={{ marginBottom: '45px', marginTop: '100px',  }}
              allowfullscreen=""
              loading="lazy"
              frameborder="0"
              referrerpolicy="no-referrer-when-downgrade"
            ></iframe>
        
          </Grid>
        </Grid>
      </Container>
    </div>
  );
};

const GridContacUSDetail =styled(Grid)`
display:flex ;
justify-content:center ;
align-items:center ;
flex-direction:column ;
background-color:#ffffff ;
min-height:223px ;
border-radius:5px ;
margin-bottom:-10% ;
`


const LabelInput = styled.label`
  color: #323232;
`;

const ButtonDiv = styled.div`
  font-weight: 700;
  text-align: center;
`;

const InputForm = styled.input`
  width: 100%;
  padding: 10px;
  border: 1px solid #a6a6a6;
  border-radius: 5px;
  position: block;
  min-height: 50px;
  margin: 6px 0 20px 0;
  :focus {
    outline: none !important;
    border-color: #6875f7;
  }
`;

const TextareaForm = styled.textarea`
  width: 100%;
  border: 1px solid #a6a6a6;
  border-radius: 5px;
  position: block;
  min-height: 112px;
  margin: 6px 0 20px 0;
  padding: 10px;
  :focus {
    outline: none !important;
    border-color: #6875f7;
  }
`;
const SubmitInput = styled.input`
  font-family: Peyda !important;
  font-weight: 700;
  background: #6875f7;
  border-radius: 5px;
  height: 45px;
  min-width: 112px;
  border: none;
  color: #fff;
  text-align: center;
  cursor: pointer;
  :hover {
    background: #4f5fff;
    border-radius: 5px;
  }
`;

const TypographyLink = styled(Typography)`
  a {
    color: #6875f7;
  }
`;

const RubikTiitle = styled(Typography)`
  font-weight: 900;
`;
const FormGrid = styled.form`
  background: #ffffff;
  box-shadow: 0px 0px 17px rgba(155, 155, 155, 0.25);
  border-radius: 5px;
  padding: 25px;
`;

const AbutusButton = styled(Button)`
  :hover {
    color: #fff;
    background-color: #4f5fff;
  }
`;

const SloganRow = styled(Grid)`
  margin-bottom: 50px;
`;

const ContainerCom = styled(Container)`
  box-shadow: 0px 0px 16px rgb(197 197 197 / 25%);
  border-radius: 52px;
  width: 80%;
  background-color: #fff;
  border: 1px solid #817e84;
  min-height: 272px;
`;

const ImgServises = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-start;
  justify-content: flex-start;
  align-items: flex-start;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;
const ImgServisesR = styled(Grid)`
  background-image: url('/images/homePage/Servises1.png');
  background-size: cover;
  height: 450px;
  display: flex;
  flex-direction: column;
  align-content: flex-end;
  justify-content: flex-end;
  align-items: flex-end;
  color: #fff;
  background-color: #000;
  border-radius: 25px;
  font-size: 1.5rem;
  line-height: 2.5;
`;

const BgBannerCenter = styled(Box)`
  background-image: url('/images/homePage/BgBannerCenter.png');
  background-size: cover;
  height: 406px;
  text-align: center;
  margin-bottom: 20%;
  border-radius: 5px;
`;

const GridPics = styled(Grid)`
  background-image: url('/images/homePage/p1.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  border-top-left-radius: 5px;
  border-bottom-left-radius: 5px;
`;
const GridPicTo = styled(Grid)`
  background-image: url('/images/homePage/p2.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  transition: all 0.5s ease;
  .secendContentPicTo {
    display: none;
  }

  .firstContentPicTo {
    display: block;
  }
  :hover {
    .firstContentPicTo {
      display: none;
    }
    .secendContentPicTo {
      display: flex;
      flex-direction: column;
      div {
        display: flex;
        align-items: center;
        justify-content: space-around;
        width: 120%;
      }
    }
  }
`;
const GridPicT = styled(Grid)`
  background-image: url('/images/homePage/p3.png');
  background-size: cover;
  height: 425px;
  display: flex;
  align-items: center;
  justify-content: center;
  color: #fff;
  border-top-right-radius: 5px;
  border-bottom-right-radius: 5px;
`;

const TypogerapyOnBanner = styled(Typography)`
  color: #fff;
  justify-content: center;
  display: flex;
  align-items: center;
  padding-top: 10%;
`;
const GoogleBox = styled(Typography)`
  margin-bottom: 50px;
  margin-top: 30px;
  border-bottom: 1px solid #323232;
  width: fit-content;
`;
const BoxContentRevies = styled(Box)`
  background: #ffffff;
  box-shadow: 0px 0px 30px rgb(181 181 181 / 25%);
  border-radius: 5px;
  min-height: 218px;
  padding: 30px;
  display: flex;
  align-items: flex-start;
  flex-direction: column;
  align-content: flex-start;
  justify-content: space-between;

  a {
    color: #4060ff;
    font-weight: 700;
  }
`;
const GridMixPic = styled(Grid)`
  z-index: 1;
  img {
    width: 100%;
  }
`;

const GridIconContent = styled(Grid)`
  display: flex;
  flex-direction: column;
  align-items: center;
  justify-content: center;
  text-align: center;
  img {
    margin-bottom: 15px;
  }
`;
const GridAboutUsBanner = styled(Grid)`
  img {
    width: 90%;
  }
`;
export const getStaticProps = async ({ locale }: HomeProps) => {
  return {
    props: {
      locale,
      ...(await serverSideTranslations(locale, ['common'], i18nConfig)),
    },
  };
};

export default Home;
